apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  labels:
    role: title
spec:
  type: NodePort  # Makes it accessible outside the cluster
  selector:
    app: restaurant-service  # Matches the label in deployment
  ports:
    - port: 8080
      targetPort: 8080  # Port on the container
      nodePort: 30001  # Accessible on port 30001 externally




