apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server  # Ensure this label matches the service selector
    spec:
      containers:
        - name: discovery-server
          image:  discovery-server:le
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server  # This must match the pod's label in the deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
