apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
data:
  STRIPE_API: c2tfdGVzdF81MVJIZWpRUlFHTnZvbGRYY1JOZ2hnWndDN3pnRXNNcnV5b0hLM3RWVHJmNmRjeVVmSmFaM0FpSzVPWW1sdzVVUENBYXFvTzlTd1drQlVIN1U2Szk3VXJUejAwWDNZMzVQYms=
  WHSEC: d2hzZWNfZjM4N2MzNTc1YWNkY2ZjNmFiZjZlYWFjYjhiMTk2MGE5ZDE3YTIyNzJmOGIzNjZhY2ZiN2ViMTE2ODljYzIyNQ==