apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9tcHNqYXlhc2VrYXJhOlgzQVVPWFFDZWFaeEUzT2FAY2x1c3RlcjAuMnk2bG10MC5tb25nb2RiLm5ldC9wYXltZW50cz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=