apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-pod
  template:
    metadata:
      labels:
        app: auth-service-pod  # Ensure this label matches the service selector
    spec:
      containers:
        - name: auth-service
          image: h4s1nth4/floo-docker:auth-service-v2
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service-pod  # This must match the pod's label in the deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: NodePort

