apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:le  # Or payment-service:latestlocal, etc.
          imagePullPolicy: Never     # If you're building inside Minikube
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30004
  type: NodePort
