apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: delivery-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP



